---

# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set up the cloudera-deploy variables
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Set up CDP Public Cloud infrastructure
      block:
        - name: Create TF input variables file for infra pre-reqs module
          ansible.builtin.template:
            src: cdp_aws_prereqs.tfvars.j2
            dest: "pbc_infra_tf/terraform.tfvars"

        - name: Terraform apply to set up the Cloud infrastructure
          # cloud.terraform.terraform: # NOTE: When use this get error similar to https://github.com/ansible-collections/cloud.terraform/issues/86
          community.general.terraform:
            project_path: "pbc_infra_tf/"
            state: "present"
            force_init: true
            # provider_upgrade: true

    - name: Set up CDP Public Cloud (Env and DL example)
      block:
        - name: Create TF input variables file for CDP deploy module
          ansible.builtin.template:
            src: cdp_aws_deploy.tfvars.j2
            dest: "pbc_deploy_tf/terraform.tfvars"
          vars:
            infra_type: "aws"
            aws_key_pair: "{{ lookup('cloud.terraform.tf_output', 'aws_key_name', project_path='pbc_infra_tf/') }}"
            aws_vpc_id: "{{ lookup('cloud.terraform.tf_output', 'aws_vpc_id', project_path='pbc_infra_tf/') }}"
            aws_public_subnet_ids: "{{ lookup('cloud.terraform.tf_output', 'aws_public_subnet_ids', project_path='pbc_infra_tf/') }}"
            aws_private_subnet_ids: "{{ lookup('cloud.terraform.tf_output', 'aws_private_subnet_ids', project_path='pbc_infra_tf/') }}"

            aws_security_group_default_id: "{{ lookup('cloud.terraform.tf_output', 'aws_security_group_default_id', project_path='pbc_infra_tf/') }}"
            aws_security_group_knox_id: "{{ lookup('cloud.terraform.tf_output', 'aws_security_group_knox_id', project_path='pbc_infra_tf/') }}"

            data_storage_location: "{{ lookup('cloud.terraform.tf_output', 'aws_data_storage_location', project_path='pbc_infra_tf/') }}"
            log_storage_location: "{{ lookup('cloud.terraform.tf_output', 'aws_log_storage_location', project_path='pbc_infra_tf/') }}"
            backup_storage_location: "{{ lookup('cloud.terraform.tf_output', 'aws_backup_storage_location', project_path='pbc_infra_tf/') }}"

            aws_xaccount_role_arn: "{{ lookup('cloud.terraform.tf_output', 'aws_xaccount_role_arn', project_path='pbc_infra_tf/') }}"
            aws_datalake_admin_role_arn: "{{ lookup('cloud.terraform.tf_output', 'aws_datalake_admin_role_arn', project_path='pbc_infra_tf/') }}"
            aws_ranger_audit_role_arn: "{{ lookup('cloud.terraform.tf_output', 'aws_ranger_audit_role_arn', project_path='pbc_infra_tf/') }}"

            aws_log_instance_profile_arn: "{{ lookup('cloud.terraform.tf_output', 'aws_log_instance_profile_arn', project_path='pbc_infra_tf/') }}"
            aws_idbroker_instance_profile_arn: "{{ lookup('cloud.terraform.tf_output', 'aws_idbroker_instance_profile_arn', project_path='pbc_infra_tf/') }}"

        - name: Terraform apply to set up CDP (may take up to 1 hour to complete)
          # cloud.terraform.terraform: # NOTE: When use this get error similar to https://github.com/ansible-collections/cloud.terraform/issues/86
          community.general.terraform:
            project_path: "pbc_deploy_tf/"
            state: "present"
            force_init: true
            # provider_upgrade: true
