---

# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set up the cloudera-deploy variables
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:

    - name: Tear down CDP Public Cloud (Env and DL example)
      block:

        - name: Terraform destroy for CDP
          # cloud.terraform.terraform:
          community.general.terraform:
            project_path: "pbc_deploy_tf/"
            state: "absent"

        - name: Remove the TF input variables file for CDP deploy module
          ansible.builtin.file:
            path: "pbc_deploy_tf/terraform.tfvars"
            state: "absent"

    - name: Tear down CDP Public Cloud infrastructure
      block:
        - name: Terraform destroy for Cloud infrastructure
          # cloud.terraform.terraform:
          community.general.terraform:
            project_path: "pbc_infra_tf/"
            state: "absent"

        - name: Remote TF input variables file for infra pre-reqs module
          ansible.builtin.file:
            dest: "pbc_infra_tf/terraform.tfvars"
            state: "absent"
