---

version: 3

images:
  base_image:
    name: ghcr.io/cloudera-labs/cldr-runner:aws-latest

dependencies:
  galaxy:
    collections:
      - name: https://github.com/jimright/cloudera.exe.git
        type: git
        version: feature/tmp_pvc
  python:
    - dnspython
