---

- name: Deprovision the infrastructure resources
  hosts: localhost
  connection: local 
  gather_facts: no
  tags:
    - teardown
    - provision
  tasks:
    - name: Deprovision the infrastructure resources in the cloud provider
      when: groups['all'] | length > 0
      ansible.builtin.import_role:
        name: cloudera.exe.provision
      vars:
        provision_state: absent
        provision_provider: "{{ infra_type }}"
        provision_inventory_file: inventory_static.ini
        provision_directory: "tf_deployment_{{ name_prefix }}_{{ infra_type }}"
        provision_state_storage: "{{ terraform.state.storage }}"
        provision_remote_storage_s3_region: "{{ terraform.state.s3_region }}"
        provision_remote_storage_s3_bucket: "{{ terraform.state.s3_bucket }}"
        provision_create_remote_storage: "{{ terraform.state.create_remote_storage }}"
        provision_name_prefix: "{{ name_prefix }}"
