---

version: 3

images:
  base_image:
    name: ghcr.io/cloudera-labs/cldr-runner:aws-latest

dependencies:
  galaxy:
    collections:
      - name: https://github.com/jimright/cloudera.exe.git
        type: git
        version: feature/tmp_pvc
      # - name: https://github.infra.cloudera.com/GOES/cloudera.infra.git
      #   type: git
      #   version: devel
      # - name: https://github.com/anisf/cloudera.cluster.git
      #   type: git
      #   version: "fix/#126"
      # - name: freeipa.ansible_freeipa
      #   version: 1.11.0
  # python:
  #   - dnspython
