---

- name: Set up CDP Private Cloud external prerequisites
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    definition_path: "./"
  tasks:
    - name: Set of deployment variables from definition.yml
      ansible.builtin.include_role:
        name: cloudera.exe.init_deployment
        public: yes
      when: init__completed is undefined

    - name: Prepare inventory for PvC Plays
      ansible.builtin.include_role:
        name: cloudera.exe.init_deployment
        public: yes
        tasks_from: prep_pvc.yml
  tags:
    - always

- name: Init run tasks for all nodes
  hosts: all
  gather_facts: no
  tasks:
    - name: Group hosts by host template and TLS
      ansible.builtin.include_role:
        name: cloudera.cluster.deployment.groupby

    - name: Check connectivity to Inventory
      ansible.builtin.wait_for_connection:
  tags:
    - always

- name: Set up external prerequisites for CDP Private Cloud
  ansible.builtin.import_playbook: cloudera.exe.pvc_base_prereqs_ext.yml

# NOTE: Cluster hosts become unavilable after krb5 client setup
# This is a temporary workaround while we debug the source of the issue
- name: Reboot all cluster hosts
  hosts: cluster
  gather_facts: no
  become: yes
  tasks:
    - name: Reboot all cluster hosts
      ansible.builtin.reboot: